# -*- coding: utf-8 -*-
"""maths.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ly-_A5K2OlqConLJcLqvOlxixUqG6RQX
"""

num1 = 368
num2 = 428
#add two numbers
sum=num1 + num2
#display the sum
print('the sum of {0} and {1} is {2}'.format(num1,num2,sum))